pybo/views/answer_views.py
from flask import Blueprint,render_template,url_for,request
from pybo.models import Question, Answer
from pybo.forms import AnswerForm
from datetime import datetime
from pybo import db
from werkzeug.utils import redirect

bp = Blueprint('answer',__name__,url_prefix='/answer')

@bp.route('/create/<int:question_id>',methods=('POST',))
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)

    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(question = question, content=content,create_date=datetime.now())
        db.session.add(answer)
        db.session.commit()

        return redirect(url_for('question.detail',question_id=question_id))

    return render_template('question/detail.html',question=question,form=form)

    # answer = Answer(content,create_date=datetime.now())
    # question.answer_set.append(answer)
    # db.session.commit()

pybo/views/question_views.py
from flask import Blueprint,render_template,request,url_for
from pybo.models import Question
from ..forms import QuestionForm, AnswerForm
from datetime import datetime
from pybo import db
from werkzeug.utils import redirect

bp = Blueprint('question',__name__,url_prefix='/question')

@bp.route('/list/')
def _list():
    page = request.args.get('page',type=int, default=1)
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page,per_page=10)
    return render_template('question/question_list.html', question_list=question_list)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form=AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/detail.html',question=question,form=form)

@bp.route('/create/', methods=('GET','POST'))
def create():
    form = QuestionForm()

    if request.method == "POST" and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data,
                            create_date=datetime.now())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('question/question_form.html',form=form)

pybo/templates/question/answer_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

pybo/templates/question/detail.html
{% extends 'base.html' %}

{% block content %}
<div class ="container my-3">
    <h2 class="border-bottom py-2"> {{ question.subject }}</h2>
    <div class="card text-white bg-dark mb-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{question.content}}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-dark p-2">
                    {{ question.create_date|datetime }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set|length }}개의 답변이 있습니다.
    </h5>
    {% for answer in question.answer_set %}
    <div class="card text-white bg-secondary mb-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{answer.create_date|datetime}}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{url_for('answer.create',question_id=question.id)}}"
          method="post" class = "my-3">

        {% for field,errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
        <strong>{{ form[field].label }}</strong> : {{ ','.join(errors) }}
        </div>
        {% endfor %}


        <div class="form-group">
        {{ form.csrf_token }}
        {{ form.content.label }}
        {{ form.content(class="form-control") }}
        </div>

        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% for field,errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong> : {{ ','.join(errors)}}
        </div>
        {% endfor %}
        {{ form.csrf_token }}
        {{ form.subject.label }}
        {{ form.subject(class="form-control") }}
        {{ form.content.label }}
        {{ form.content(class="form-control") }}

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
<!--<link rel="stylesheet" href="{{url_for('static',filename='bootstrap.min.css')}}">-->
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
        <table class="table">
            <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일자</th>
            </tr>
            </thead>
            <tbody>
                {% if question_list %}
                {% for question in question_list.items %}
                <tr>
                    <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
                    <td>
                        <a href="{{ url_for('question.detail', question_id=question.id) }}">
                            {{ question.subject }} </a>
                        {% if question.answer_set|length >0 %}
                        <span class="text-danger small ml-2">{{question.answer_set|length}}</span>
                        {% endif %}
                    </td>
                    <td>
                        {{ question.create_date|datetime }}
                    </td>
                </tr>
                {% endfor %}
                {% endif %}

            </tbody>
        </table>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if question_list.has_prev %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            {% for page_num in question_list.iter_pages() %}
                {% if page_num %}
                    {% if page_num != question_list.page %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                    {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </li>
                    {% endif %}
               {% else %}
                    <li class="disabled">
                        <a class="page-link" href="#">...</a>
                    </li>
               {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
        <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문등록하기</a>

</div>
{% endblock %}