pybo/views/auth_views.py
from flask import Blueprint, render_template, request, url_for, flash, session, g
from werkzeug.security import generate_password_hash, check_password_hash

from pybo.models import Question, User
from ..forms import UserCreateForm, UserLoginForm
from datetime import datetime
from pybo import db
from werkzeug.utils import redirect

bp = Blueprint('auth',__name__,url_prefix='/auth')



@bp.route('/signup/',methods=('GET','POST'))
def signup():
    form = UserCreateForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user=User(username=form.username.data,
                      password=generate_password_hash(form.password1.data),
                      email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')

    return render_template('auth/signup.html',form=form)

@bp.route('/login/',methods=('GET','POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = '존재하지 않는 사용자입니다.'
        elif not check_password_hash(user.password,form.password.data):
            error = '비밀번호가 올바르지 않습니다.'
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))

        flash(error)

    return render_template('auth/login.html',form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else :
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

pybo/views/movie_views.py
from flask import Blueprint, render_template, url_for, request
from werkzeug.utils import redirect
from pybo.movieapi import Mrank, navermovie
from ..forms import MovieForm


bp = Blueprint('movie', __name__, url_prefix='/movie')


@bp.route('/rank/')
def Movierank():
    rankdata = Mrank()


    return render_template('movie/movierank.html',rankdata=rankdata)

@bp.route('/search/', methods=('GET','POST'))
def Moviesearch():
    form = MovieForm()

    if request.method == "POST" and form.validate_on_submit():
        #post로 들어오고 데이터가 오류가 아니면, 제대로 들어왔으면
        search = navermovie(form.search.data)
        return render_template('movie/navermovie.html', searchmovie=search['items'], form=form)

    return render_template('movie/navermovie.html',form=form)

pybo/views/naver_views.py
from flask import Blueprint, render_template, url_for, request
from werkzeug.utils import redirect
from pybo.naverapi import naverbook
from ..forms import NaverBookForm

bp = Blueprint('naver', __name__, url_prefix='/naver')


@bp.route('/book/', methods=('GET','POST'))
def Naverbook():
    form = NaverBookForm()

    if request.method == "POST" and form.validate_on_submit():
        #post로 들어오고 데이터가 오류가 아니면, 제대로 들어왔으면
        result = naverbook(form.search.data)
        return render_template('naver/naverbook.html', bookinfo_list=result['items'], form=form)

    return render_template('naver/naverbook.html',form=form)

pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{url_for('static',filename='bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
    <title>Hello, pybo!!</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index')}}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">

        {% if g.user %}.
        <ul class="navbar-nav">
             <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('movie.Movierank')}}">영화순위</a>
             </li>
             <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('movie.Moviesearch')}}">영화검색</a>
             </li>
            <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('naver.Naverbook')}}">네이버책</a>
             </li>
             <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('auth.logout')}}">{{g.username}}님 로그아웃</a>
             </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('movie.Movierank')}}">영화순위</a>
             </li>
             <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('movie.Moviesearch')}}">영화검색</a>
             </li>
             <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('naver.Naverbook')}}">네이버책</a>
             </li>
            <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('auth.signup') }}">계정생성</a>
            </li>
             <li class="navbar-nav">
                <a class="nav-link" href="{{url_for('auth.login')}}">로그인</a>
             </li>
        </ul>
        {% endif %}
    </div>
</nav>

{% block content %}
{% endblock %}

<script src="{{url_for('static',filename='jquery-3.6.0.min.js')}}"></script>
<script src="{{url_for('static',filename='bootstrap.min.css')}}"></script>
</body>
</html>